#!/usr/bin/env python3

"""
This is a place holder script for bootstrapping a workspace.

The actual script which is installed is generated by python-setuptools.
"""

import importlib
import os
import sys

# add ament_tools to the Python path
ament_tools_root = os.path.join(os.path.dirname(__file__), '..')
sys.path.insert(0, os.path.abspath(ament_tools_root))

# check if ament_package is in a sibling folder
ament_package_root = os.path.join(ament_tools_root, '..', 'ament_package')
if os.path.exists(ament_package_root):
    # and add it to the Python path
    sys.path.insert(1, os.path.abspath(ament_package_root))
try:
    import ament_package
except ImportError as e:
    raise ImportError(("%s\nTry cloning 'ament_package' into a sibling " +
                       "folder of 'ament_tools'") % e)

# check if osrf_pycommon is in a sibling folder
osrf_pycommon_root = os.path.join(ament_tools_root, '..', 'osrf_pycommon')
if os.path.exists(osrf_pycommon_root):
    # and add it to the Python path
    sys.path.insert(1, os.path.abspath(osrf_pycommon_root))
try:
    import osrf_pycommon
except ImportError as e:
    raise ImportError(("%s\nTry cloning 'osrf_pycommon' into a sibling " +
                       "folder of 'ament_tools'") % e)

# override verb discovery relying on pkg_resources entry points
from osrf_pycommon.cli_utils import verb_pattern


def list_verbs(group):
    assert group == 'ament.verbs'
    verbs = [
        'build',
        'build_pkg',
        'list_packages',
        'package_name',
        'package_version',
        'test',
        'test_pkg',
        'test_results'
    ]
    return verbs

verb_pattern.list_verbs = list_verbs


def load_verb_description(verb_name, group):
    verb_module = importlib.import_module('ament_tools.verbs.%s' % verb_name)
    return verb_module.entry_point_data

verb_pattern.load_verb_description = load_verb_description


# override build type discovery relying on pkg_resources entry points
known_build_types = {
    'ament_cmake': 'AmentCmakeBuildType',
    'ament_python': 'AmentPythonBuildType',
}


def yield_supported_build_types(name=None):
    class Loader(object):
        def __init__(self, build_type, entry_point):
            self.build_type = build_type
            self.entry_point = entry_point

        def load(self):
            build_type_module = importlib.import_module(
                'ament_tools.build_types.%s' % self.build_type)
            return getattr(build_type_module, self.entry_point)

    if name is None:
        return [Loader(build_type, entry_point)
                for build_type, entry_point in known_build_types.items()]

    if name not in known_build_types:
        raise RuntimeError(
            "This script does not support the build type '%s'\n" % name +
            'Only the following build types are supported: %s' %
            ', '.join(known_build_types.keys()))
    return Loader(name, known_build_types[name])


def get_class_for_build_type(build_type):
    loader = yield_supported_build_types(build_type)
    return loader.load()


from ament_tools import build_type_discovery

build_type_discovery.yield_supported_build_types = yield_supported_build_types
build_type_discovery.get_class_for_build_type = get_class_for_build_type


from ament_tools.commands.ament import main

if __name__ == '__main__':
    sys.exit(main() or 0)
